In [ ]:
import numpy as np

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]],dtype=float)
arr

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]])

In [ ]:
print(arr.ndim)

3


In [ ]:
print(arr.shape)

(2, 3, 3)


In [ ]:
print(arr.size)

18


In [ ]:
print(arr.dtype)

float64


In [ ]:
lis = [5,6,7,8,9]
arr2 = np.array(lis)
print(arr2)

[5 6 7 8 9]


In [ ]:
print(arr2.dtype)

int64


In [ ]:
type(lis)

list

In [ ]:
zz = np.zeros((3,3))
zz

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ff = np.full((3,5),6,complex)
ff

array([[6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j]])

In [ ]:
ran = np.random.random((2,2))
ran

array([[0.57408788, 0.42487695],
       [0.23201367, 0.27780861]])

In [ ]:
f = np.arange(0,100,5)
f

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [ ]:
l = np.linspace(0,1,num=100)
l


array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
t = np.linspace(0,50)
t

array([ 0.        ,  1.02040816,  2.04081633,  3.06122449,  4.08163265,
        5.10204082,  6.12244898,  7.14285714,  8.16326531,  9.18367347,
       10.20408163, 11.2244898 , 12.24489796, 13.26530612, 14.28571429,
       15.30612245, 16.32653061, 17.34693878, 18.36734694, 19.3877551 ,
       20.40816327, 21.42857143, 22.44897959, 23.46938776, 24.48979592,
       25.51020408, 26.53061224, 27.55102041, 28.57142857, 29.59183673,
       30.6122449 , 31.63265306, 32.65306122, 33.67346939, 34.69387755,
       35.71428571, 36.73469388, 37.75510204, 38.7755102 , 39.79591837,
       40.81632653, 41.83673469, 42.85714286, 43.87755102, 44.89795918,
       45.91836735, 46.93877551, 47.95918367, 48.97959184, 50.        ])

In [ ]:
arr

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]])

In [ ]:
arr.shape

(2, 3, 3)

In [ ]:
n_arr = arr.reshape(1,2,9)
n_arr

array([[[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14., 15., 16., 17., 18.]]])

In [ ]:
flat = arr.flatten()
flat

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

In [ ]:
arr  

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]],

       [[10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]]])

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=float)
arr2

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
arr2[1:3,::]

array([[4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
cond = arr > 2
arr[cond]

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15.,
       16., 17., 18.])

In [ ]:
print("arr2 = ",arr2)
print()
print("arr2 t = ",arr2.T)

arr2 =  [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

arr2 t =  [[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [ ]:
arr2*(arr2.T)

array([[ 1.,  8., 21.],
       [ 8., 25., 48.],
       [21., 48., 81.]])

In [ ]:
print(arr2.max(axis = 1))
print(arr2.max(axis = 0))

[3. 6. 9.]
[7. 8. 9.]


In [ ]:
print(arr2.sum(axis = 0))
print(arr2.sum(axis = 1))

[12. 15. 18.]
[ 6. 15. 24.]


In [ ]:
arr2.cumsum(axis = 1)

array([[ 1.,  3.,  6.],
       [ 4.,  9., 15.],
       [ 7., 15., 24.]])

In [ ]:
a = arr2
b = arr2.T
a.b

AttributeError: ignored